/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
package io.treehopper.libraries.sensors.pressure.bmp280;

 enum Filters
{
    FilterOff (0),
    Filter2 (1),
    Filter4 (2),
    Filter8 (3),
    Filter16 (4);

int val;

Filters(int val) { this.val = val; }
public int getVal() { return val; }
}
