using System;
using System.ComponentModel;

namespace Treehopper
{
    /// <summary>
    /// Defines whether a signal is active high (rising-edge) or active low (falling-edge)
    /// </summary>
    public enum PinPolarity
    {

        /// <summary>
        /// The signal is considered active when the signal is low
        /// </summary>
        ActiveLow,
        /// <summary>
        /// The signal is considered active when the signal is high
        /// </summary>
        ActiveHigh
    };

    public enum AdcReferenceLevel
    {
        /// <summary>
        /// 3.3V rail generated by on-board LDO, rated at 1.5% accuracy.
        /// </summary>
        VREF_3V3,

        /// <summary>
        /// 1.65V reference rated at 1.8% accuracy. 
        /// </summary>
        VREF_1V65,

        /// <summary>
        /// 1.8V reference. Accuracy TBD.
        /// </summary>
        VREF_1V8,

        /// <summary>
        /// 2.4V reference rated at 2.1% accuracy.
        /// </summary>
        VREF_2V4,

        /// <summary>
        /// 3.3V supply derived from the 1.65V reference rated at 3.6% accuracy.
        /// </summary>
        VREF_3V3_DERIVED,

        /// <summary>
        /// 3.6V reference derived from the 1.8V LDO. Accuracy TBD.
        /// </summary>
        VREF_3V6

        // These are pointless, since ADC voltage is clamped to 3.6V
        //VREF_4V8,
        //VREF_6V6,
    }

    /// <summary>
    /// This is the delegate prototype used for event-driven reading of digital pins.
    /// </summary>
    /// <param name="sender">The Pin that changed</param>
    /// <param name="value">The new value of the pin</param>
    public delegate void OnDigitalInValueChanged(Pin sender, bool value);

    internal enum PinConfigCommands
    {
        MakeDigitalInput = 0x00,
        MakePushPullOutput,
        MakeOpenDrainOutput,
        MakeAnalogInput,
        SetDigitalValue,
        GetDigitalValue,
        GetAnalogValue
    }

    public enum PinMode { Reserved, DigitalInput, PushPullOutput, OpenDrainOutput, AnalogInput, Unassigned };
    
    /// <summary>
    /// The interrupt mode of the pin.
    /// </summary>
    public enum PinInterruptMode {
        /// <summary>
        /// Interrupts disabled.
        /// </summary>
        NoInterrupt, 
        
        /// <summary>
        /// Interrupt occurs when pin transitions from low to high.
        /// </summary>
        Rising, 
        
        /// <summary>
        /// Interrupt occurs when pin transitions from high to low
        /// </summary>
        Falling, 
        
        /// <summary>
        /// Interrupt occurs when pin transitions from either low to high, or from high to low.
        /// </summary>
        RisingFalling 
    };

    public enum OutputType
    {
        PushPull,

        OpenDrain
    }

    /// <summary>
    /// Used to send VoltageChanged events from the AnalogIn pin.
    /// </summary>
    /// <param name="sender">The AnalogIn pin that sent that message</param>
    /// <param name="voltage">The new voltage of the AnalogIn pin</param>
    public delegate void OnAnalogInVoltageChanged(Pin sender, double voltage);

    /// <summary>
    /// Used to send ValueChanged events from the AnalogIn pin.
    /// </summary>
    /// <param name="sender">The AnalogIn pin that sent that message</param>
    /// <param name="value">The new voltage of the AnalogIn pin</param>
    public delegate void OnAnalogInValueChanged(Pin sender, int value);

    /// <summary>
    /// Pin is the base class for all Treehopper pins. It provides core digital I/O (GPIO) functionality.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This class is useful when only core GPIO functions are needed, and the user wishes to make code portable
    /// between pins. While it cannot be instantiated directly by the user, Pin variables can reference existing pins.
    /// </para>
    /// </remarks>
    public class Pin : INotifyPropertyChanged
    {
        protected string ioName;
        /// <summary>
        /// The PIC16F1459 pin name
        /// </summary>
        public string IOName { get { return ioName; } }

        private TreehopperUsb board;
        /// <summary>
        /// This returns a reference to the Treehopper board this pin belongs to.
        /// </summary>
        public TreehopperUsb Board { get { return board; } }

        PinInterruptMode interruptMode;
        bool digitalValue;

        private PinMode mode = PinMode.Unassigned;
        public PinMode Mode
        {
            get
            {
                return mode;
            }
            set
            {
                if (value == mode)
                    return;
                if(mode == PinMode.Reserved && value != PinMode.Unassigned)
                {
                    throw new Exception("This pin is reserved; you must disable the peripheral using it before interacting with it");
                }

                mode = value;

                switch (mode)
                {
                    case PinMode.AnalogInput:
                        SendCommand(new byte[] { (byte)PinConfigCommands.MakeAnalogInput, (byte)ReferenceLevel });
                        break;
                    case PinMode.DigitalInput:
                        SendCommand(new byte[] { (byte)PinConfigCommands.MakeDigitalInput, (byte)interruptMode });
                        break;
                    case PinMode.OpenDrainOutput:
                        SendCommand(new byte[] { (byte)PinConfigCommands.MakeOpenDrainOutput, (byte)interruptMode });
                        break;
                    case PinMode.PushPullOutput:
                        SendCommand(new byte[] { (byte)PinConfigCommands.MakePushPullOutput, (byte)interruptMode });
                        break;
                }


            }
        }

        /// <summary>
        /// Occurs when the input on the pin changes.
        /// </summary>
        /// <remarks>
        /// This event will only fire when the pin is configured as a digital input.
        /// </remarks>
        public event OnDigitalInValueChanged DigitalValueChanged;

        /// <summary>
        /// The pin number of the pin.
        /// </summary>
        public int PinNumber { get; set; }

        /// <summary>
        /// The SoftPwm functions associated with this pin.
        /// </summary>
        public SoftPwm SoftPwm { get; set;}
        
        internal Pin(TreehopperUsb board, byte pinNumber)
        {
            this.board = board;
            this.PinNumber = pinNumber;
            interruptMode = PinInterruptMode.NoInterrupt;
            SoftPwm = new SoftPwm(Board, this);
            AdcValueChangedThreshold = 2;
            AdcVoltageChangedThreshold = 0.05;
            this.ReferenceLevel = AdcReferenceLevel.VREF_3V3;
        }

        /// <summary>
        /// The interrupt mode of the pin.
        /// </summary>
        /// <remarks>
        /// <para>Since the board always polls Treehopper (USB forbids devices from initiating communication), enabling an interrupt does not provide
        /// performance or timing improvements. However, it is useful when you wish to detect extremely short pulses that may occur faster than the
        /// pin refresh rate (which is system-dependent, but usually on the order of 1-5 kHz).</para>
        /// <para>
        /// Not all pins support interrupts. If a pin does not support an interrupt, it will override this property as read-only, and return <see cref="PinInterruptMode.NoInterrupt"/>.
        /// </para>
        /// </remarks>
        public virtual PinInterruptMode InterruptMode
        {
            get
            {
                return interruptMode;
            }
            set
            {
                if(value != interruptMode) // We have to re-issue the MakeDigitalInput command
                {
                    interruptMode = value;
                    RaisePropertyChanged("InterruptMode");
                    if(Mode == PinMode.DigitalInput) // People are stupid and might change the interrupt mode of the pin while it's not an input!
                    {
                        SendCommand(new byte[] { (byte)PinConfigCommands.MakeDigitalInput, (byte)interruptMode });
                    }
                }
            }
        }

        /// <summary>
        /// Gets or sets the voltage threshold required to fire the VoltageChanged event.
        /// </summary>
        public double AdcVoltageChangedThreshold { get; set; }
        
        /// <summary>
        /// Gets or sets the value threshold required to fire the ValueChanged event.
        /// </summary>
        public int AdcValueChangedThreshold { get; set; }

        /// <summary>
        /// Gets or sets the digital value of the pin.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Setting a value to a pin that is configured as an input will automatically make the pin an output before 
        /// writing the value to it. 
        /// </para>
        /// <para>
        /// The value retrieved from this pin will read as "0" when then pin is being used for other purposes.
        /// </para>
        /// </remarks>
        public bool DigitalValue
        {
            get
            {
                return digitalValue;
            }
            set
            {
                digitalValue = value;
                if (!(Mode == PinMode.PushPullOutput || Mode == PinMode.OpenDrainOutput))
                    Mode = PinMode.PushPullOutput; // assume they want push-pull
                byte byteVal = (byte)(digitalValue ? 0x01 : 0x00);
                SendCommand(new byte[] { (byte)PinConfigCommands.SetDigitalValue, byteVal});
            }
        }

        /// <summary>
        /// Toggles the output value of the pin.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Calling this function on a pin that is configured as an input will automatically make the pin an output
        /// before writing the value to it.
        /// </para>
        /// </remarks>
        /// <example>
        /// In this example, an LED attached to pin 4 is made to blink.
        /// <code>
        /// Pin led = myTreehopperBoard.Pin4; // create a reference to Pin4 to keep code concise.
        /// led.MakeDigitalOutput();
        /// while(true)
        /// {
        ///     led.Toggle();
        ///     Thread.Sleep(500);
        /// }
        /// </code>
        /// </example>
        public void ToggleOutput()
        {
            DigitalValue = !DigitalValue;
        }

        internal void RaiseDigitalInValueChanged()
        {
            if (DigitalValueChanged != null)
            {
                DigitalValueChanged(this, digitalValue);
            }
        }

        internal void SendCommand(byte[] cmd)
        {
            byte[] data = new byte[64];
            data[0] = (byte)DeviceCommands.PinConfig;
            data[1] = (byte)PinNumber;
            cmd.CopyTo(data, 2);
            Board.sendPinConfigPacket(data);
        }

        private int prevAnalogVal;
        private double prevAnalogVoltage;

        internal virtual void UpdateValue(byte highByte, byte lowByte)
        {
            if(Mode == PinMode.DigitalInput)
            {
                bool newVal = highByte > 0;
                if (digitalValue != newVal) // we have a new value!
                {
                    digitalValue = newVal;
                    RaiseDigitalInValueChanged();
                    RaisePropertyChanged("DigitalValue");
                }
            } else if(Mode == PinMode.AnalogInput)
            {
                int val = ((int)highByte) << 8;
                val |= (int)lowByte;
                val >>= 1;
                this.adcVoltage = Math.Round((double)val * (referenceLevelVoltage / 4092.0), 3);

                this.adcValue = val;

                if (Math.Abs(prevAnalogVal - val) > AdcValueChangedThreshold)
                {
                    prevAnalogVal = val;
                    if (AnalogValueChanged != null)
                    {
                        AnalogValueChanged(this, adcValue);
                    }
                }

                if (Math.Abs(prevAnalogVoltage - adcVoltage) > AdcVoltageChangedThreshold)
                {
                    prevAnalogVoltage = adcVoltage;
                    if (AnalogVoltageChanged != null)
                    {
                        AnalogVoltageChanged(this, adcVoltage);
                    }
                }

                // Regardless of whether we exceeded our threshold, fire the PropertyChanged events
                RaisePropertyChanged("AdcValue");
                RaisePropertyChanged("AdcVoltage");
                RaisePropertyChanged("AdcPercent");
                
            }
            
        }

        /// <summary>
        /// Occurs when an analog voltage is changed.
        /// </summary>
        /// <remarks>
        /// The Changed event is raised when the 10-bit ADC value obtained is different from the previous reading.
        /// </remarks>
        public event OnAnalogInVoltageChanged AnalogVoltageChanged;

        /// <summary>
        /// Occurs when an analog value is changed.
        /// </summary>
        /// <remarks>
        /// The Changed event is raised when the 10-bit ADC value obtained is different from the previous reading.
        /// </remarks>
        public event OnAnalogInValueChanged AnalogValueChanged;
        double adcVoltage;
        int adcValue;


        /// <summary>
        /// Retrieve the last value obtained from the ADC. 
        /// </summary>
        /// <remarks>
        /// Treehopper has a 12-bit ADC, so ADC values will range from 0-4096.
        /// </remarks>
        public int AdcValue
        {
            get
            {
                return this.adcValue;
            }
        }

        /// <summary>
        /// Retrieve the last voltage reading from the ADC.
        /// </summary>
        /// <remarks>
        /// This property assumes VBUS, the supply voltage, is equivalent to 5V. 
        /// Since the actual VBUS will be higher or lower, the value returned from this property shouldn't be assumed to be exact. 
        /// Since many sensors are ratiometric, and since most users will power these sensors from VBUS, it is safe to assume 
        /// that 0V represents 0%, 2.5V represents 50% and 5V represents 100% readout.
        /// </remarks>
        public double AdcVoltage
        {
            get
            {
                return this.adcVoltage;
            }
        }

        /// <summary>
        /// Retrieve the last reading from the Adc, expressed as a percent of VREF
        /// </summary>
        /// <remarks>
        /// </remarks>
        public double AdcPercent
        {
            get
            {
                return this.AdcPercent;
            }
        }

        double referenceLevelVoltage;

        AdcReferenceLevel referenceLevel;

        /// <summary>
        /// Sets the ADC reference value used 
        /// </summary>
        public AdcReferenceLevel ReferenceLevel
        {
            get
            {
                return referenceLevel;
            }
            set
            {
                referenceLevel = value;
                switch(referenceLevel)
                {
                    case AdcReferenceLevel.VREF_1V65:
                        referenceLevelVoltage = 1.65;
                        break;
                    case AdcReferenceLevel.VREF_1V8:
                        referenceLevelVoltage = 1.8;
                        break;
                    case AdcReferenceLevel.VREF_2V4:
                        referenceLevelVoltage = 2.4;
                        break;
                    case AdcReferenceLevel.VREF_3V3:
                        referenceLevelVoltage = 3.3;
                        break;
                    case AdcReferenceLevel.VREF_3V3_DERIVED:
                        referenceLevelVoltage = 3.3;
                        break;
                    case AdcReferenceLevel.VREF_3V6:
                        referenceLevelVoltage = 3.6;
                        break;
                    //case AdcReferenceLevel.VREF_4V8:
                    //    referenceLevelVoltage = 4.8;
                    //    break;
                    //case AdcReferenceLevel.VREF_6V6:
                    //    referenceLevelVoltage = 6.6;
                    //    break;
                }

                // if we're already an analog input, re-send the command to set the new reference level
                if (Mode == PinMode.AnalogInput)
                    SendCommand(new byte[] { (byte)PinConfigCommands.MakeAnalogInput, (byte)ReferenceLevel });
            }
        }

        /// <summary>
        /// This event fires whenever a property changes
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        internal void RaisePropertyChanged(string property)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(property));
        }
    }
}
