/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
package io.treehopper.libraries.sensors.inertial.lis3dsh;

 enum Bandwidths
{
    Hz_800 (0),
    Hz_200 (1),
    Hz_400 (2),
    Hz_50 (3);

int val;

Bandwidths(int val) { this.val = val; }
public int getVal() { return val; }
}
