/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
package io.treehopper.libraries.sensors.inertial.lis3dsh;

 enum Fscales
{
    g_2 (0),
    g_4 (1),
    g_6 (2),
    g_8 (3),
    g_16 (4);

int val;

Fscales(int val) { this.val = val; }
public int getVal() { return val; }
}
