/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
package io.treehopper.libraries.sensors.inertial.lsm303dlhcaccel;

 enum AccelhighPassModes
{
    Reset (0),
    ReferenceSignal (1),
    Normal (2),
    AutoResetOnInterrupt (3);

int val;

AccelhighPassModes(int val) { this.val = val; }
public int getVal() { return val; }
}
