/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
package io.treehopper.libraries.sensors.optical.isl29125;

public enum InterruptSelections
{
    NoInterrupt (0),
    Green (1),
    Red (2),
    Blue (3);

int val;

InterruptSelections(int val) { this.val = val; }
public int getVal() { return val; }
}
