/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
package io.treehopper.libraries.sensors.optical.tsl2561;

public enum IntegrationTimings
{
    Time_13_7ms (0),
    Time_101ms (1),
    Time_402ms (2),
    Time_Manual (3);

int val;

IntegrationTimings(int val) { this.val = val; }
public int getVal() { return val; }
}
