/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
package io.treehopper.libraries.sensors.optical.tsl2561;

 enum Powers
{
    powerDown (0),
    powerUp (3);

int val;

Powers(int val) { this.val = val; }
public int getVal() { return val; }
}
