package io.treehopper.libraries.sensors.optical.vcnl4010;

import io.treehopper.libraries.RegisterManager;
import io.treehopper.libraries.Register;
import io.treehopper.SMBusDevice;
import java.util.Arrays;

/// This file was auto-generated by RegisterGenerator. Any changes to it will be overwritten!
class Vcnl4010Registers extends RegisterManager
{
    SMBusDevice _dev;
    Vcnl4010Registers(SMBusDevice dev)
    {
        super(dev);
        command = new CommandRegister(this);
        _registers.add(command);
        productId = new ProductIdRegister(this);
        _registers.add(productId);
        proximityRate = new ProximityRateRegister(this);
        _registers.add(proximityRate);
        ledCurrent = new LedCurrentRegister(this);
        _registers.add(ledCurrent);
        ambientLightParameters = new AmbientLightParametersRegister(this);
        _registers.add(ambientLightParameters);
        ambientLightResult = new AmbientLightResultRegister(this);
        _registers.add(ambientLightResult);
        proximityResult = new ProximityResultRegister(this);
        _registers.add(proximityResult);
        interruptControl = new InterruptControlRegister(this);
        _registers.add(interruptControl);
        lowThreshold = new LowThresholdRegister(this);
        _registers.add(lowThreshold);
        highThreshold = new HighThresholdRegister(this);
        _registers.add(highThreshold);
        interruptStatus = new InterruptStatusRegister(this);
        _registers.add(interruptStatus);
        proxModulatorTimingAdustment = new ProxModulatorTimingAdustmentRegister(this);
        _registers.add(proxModulatorTimingAdustment);
    }

    CommandRegister command;
    ProductIdRegister productId;
    ProximityRateRegister proximityRate;
    LedCurrentRegister ledCurrent;
    AmbientLightParametersRegister ambientLightParameters;
    AmbientLightResultRegister ambientLightResult;
    ProximityResultRegister proximityResult;
    InterruptControlRegister interruptControl;
    LowThresholdRegister lowThreshold;
    HighThresholdRegister highThreshold;
    InterruptStatusRegister interruptStatus;
    ProxModulatorTimingAdustmentRegister proxModulatorTimingAdustment;

    class CommandRegister extends Register
    {
        CommandRegister(RegisterManager regManager) { super(regManager, 0x80, 1, false); }

        int selfTimedEnable;
        int proxPeriodicEnable;
        int alsPeriodicEnable;
        int proxOnDemandStart;
        int alsOnDemandStart;
        int proxDataReady;
        int alsDataReady;
        int configLock;


        public CommandRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((SelfTimedEnable & 0x1) << 0) | ((ProxPeriodicEnable & 0x1) << 1) | ((AlsPeriodicEnable & 0x1) << 2) | ((ProxOnDemandStart & 0x1) << 3) | ((AlsOnDemandStart & 0x1) << 4) | ((ProxDataReady & 0x1) << 5) | ((AlsDataReady & 0x1) << 6) | ((ConfigLock & 0x1) << 7); }
        public void setValue(long _value)
        {
            SelfTimedEnable = (int)((_value >> 0) & 0x1);
            ProxPeriodicEnable = (int)((_value >> 1) & 0x1);
            AlsPeriodicEnable = (int)((_value >> 2) & 0x1);
            ProxOnDemandStart = (int)((_value >> 3) & 0x1);
            AlsOnDemandStart = (int)((_value >> 4) & 0x1);
            ProxDataReady = (int)((_value >> 5) & 0x1);
            AlsDataReady = (int)((_value >> 6) & 0x1);
            ConfigLock = (int)((_value >> 7) & 0x1);
        }
    }
    class ProductIdRegister extends Register
    {
        ProductIdRegister(RegisterManager regManager) { super(regManager, 0x82, 1, false); }

        int revisionId;
        int productId;


        public ProductIdRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((RevisionId & 0xF) << 0) | ((ProductId & 0xF) << 4); }
        public void setValue(long _value)
        {
            RevisionId = (int)((_value >> 0) & 0xF);
            ProductId = (int)((_value >> 4) & 0xF);
        }
    }
    class ProximityRateRegister extends Register
    {
        ProximityRateRegister(RegisterManager regManager) { super(regManager, 0x82, 1, false); }

        int rate;

                public rate getRate() { for (rate b : rate.values()) { if(b.getVal() == Rate) return b; } return rate.values()[0]; }
                public void setRate(rate enumVal) { Rate = enumVal.getVal(); }

        public ProximityRateRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((Rate & 0xF) << 0); }
        public void setValue(long _value)
        {
            Rate = (int)((_value >> 0) & 0xF);
        }
    }
    class LedCurrentRegister extends Register
    {
        LedCurrentRegister(RegisterManager regManager) { super(regManager, 0x83, 1, false); }

        int irLedCurrentValue;
        int fuseProgId;


        public LedCurrentRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((IrLedCurrentValue & 0x3F) << 0) | ((FuseProgId & 0x3) << 6); }
        public void setValue(long _value)
        {
            IrLedCurrentValue = (int)((_value >> 0) & 0x3F);
            FuseProgId = (int)((_value >> 6) & 0x3);
        }
    }
    class AmbientLightParametersRegister extends Register
    {
        AmbientLightParametersRegister(RegisterManager regManager) { super(regManager, 0x84, 1, false); }

        int averagingSamples;
        int autoOffsetCompensation;
        int alsRate;
        int continuousConversionMode;

                public alsRate getAlsRate() { for (alsRate b : alsRate.values()) { if(b.getVal() == AlsRate) return b; } return alsRate.values()[0]; }
                public void setAlsRate(alsRate enumVal) { AlsRate = enumVal.getVal(); }

        public AmbientLightParametersRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((AveragingSamples & 0x7) << 0) | ((AutoOffsetCompensation & 0x1) << 3) | ((AlsRate & 0x7) << 4) | ((ContinuousConversionMode & 0x1) << 7); }
        public void setValue(long _value)
        {
            AveragingSamples = (int)((_value >> 0) & 0x7);
            AutoOffsetCompensation = (int)((_value >> 3) & 0x1);
            AlsRate = (int)((_value >> 4) & 0x7);
            ContinuousConversionMode = (int)((_value >> 7) & 0x1);
        }
    }
    class AmbientLightResultRegister extends Register
    {
        AmbientLightResultRegister(RegisterManager regManager) { super(regManager, 0x85, 2, false); }

        int value;


        public AmbientLightResultRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((Value & 0xFFFF) << 0); }
        public void setValue(long _value)
        {
            Value = (int)((_value >> 0) & 0xFFFF);
        }
    }
    class ProximityResultRegister extends Register
    {
        ProximityResultRegister(RegisterManager regManager) { super(regManager, 0x87, 2, true); }

        int value;


        public ProximityResultRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((Value & 0xFFFF) << 0); }
        public void setValue(long _value)
        {
            Value = (int)((_value >> 0) & 0xFFFF);
        }
    }
    class InterruptControlRegister extends Register
    {
        InterruptControlRegister(RegisterManager regManager) { super(regManager, 0x89, 1, false); }

        int interruptThresholdSelect;
        int interruptThresholdEnable;
        int interruptAlsReadyEnable;
        int intCountExceed;

                public intCountExceed getIntCountExceed() { for (intCountExceed b : intCountExceed.values()) { if(b.getVal() == IntCountExceed) return b; } return intCountExceed.values()[0]; }
                public void setIntCountExceed(intCountExceed enumVal) { IntCountExceed = enumVal.getVal(); }

        public InterruptControlRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((InterruptThresholdSelect & 0x1) << 0) | ((InterruptThresholdEnable & 0x1) << 1) | ((InterruptAlsReadyEnable & 0x1) << 2) | ((IntCountExceed & 0x7) << 5); }
        public void setValue(long _value)
        {
            InterruptThresholdSelect = (int)((_value >> 0) & 0x1);
            InterruptThresholdEnable = (int)((_value >> 1) & 0x1);
            InterruptAlsReadyEnable = (int)((_value >> 2) & 0x1);
            IntCountExceed = (int)((_value >> 5) & 0x7);
        }
    }
    class LowThresholdRegister extends Register
    {
        LowThresholdRegister(RegisterManager regManager) { super(regManager, 0x8A, 2, true); }

        int value;


        public LowThresholdRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((Value & 0xFFFF) << 0); }
        public void setValue(long _value)
        {
            Value = (int)((_value >> 0) & 0xFFFF);
        }
    }
    class HighThresholdRegister extends Register
    {
        HighThresholdRegister(RegisterManager regManager) { super(regManager, 0x8C, 2, true); }

        int value;


        public HighThresholdRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((Value & 0xFFFF) << 0); }
        public void setValue(long _value)
        {
            Value = (int)((_value >> 0) & 0xFFFF);
        }
    }
    class InterruptStatusRegister extends Register
    {
        InterruptStatusRegister(RegisterManager regManager) { super(regManager, 0x8E, 1, false); }

        int intThresholdHighExceeded;
        int intThresholdLowExceeded;
        int intAlsReady;
        int intProxReady;


        public InterruptStatusRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((IntThresholdHighExceeded & 0x1) << 0) | ((IntThresholdLowExceeded & 0x1) << 1) | ((IntAlsReady & 0x1) << 2) | ((IntProxReady & 0x1) << 3); }
        public void setValue(long _value)
        {
            IntThresholdHighExceeded = (int)((_value >> 0) & 0x1);
            IntThresholdLowExceeded = (int)((_value >> 1) & 0x1);
            IntAlsReady = (int)((_value >> 2) & 0x1);
            IntProxReady = (int)((_value >> 3) & 0x1);
        }
    }
    class ProxModulatorTimingAdustmentRegister extends Register
    {
        ProxModulatorTimingAdustmentRegister(RegisterManager regManager) { super(regManager, 0x8F, 1, false); }

        int modulationDeadTime;
        int proximityFrequency;
        int modulationDelayTime;


        public ProxModulatorTimingAdustmentRegister read()
        {
            manager.read(this);
            return this;
        }

        public long getValue() { return ((ModulationDeadTime & 0x7) << 0) | ((ProximityFrequency & 0x3) << 3) | ((ModulationDelayTime & 0x7) << 5); }
        public void setValue(long _value)
        {
            ModulationDeadTime = (int)((_value >> 0) & 0x7);
            ProximityFrequency = (int)((_value >> 3) & 0x3);
            ModulationDelayTime = (int)((_value >> 5) & 0x7);
        }
    }
}
